from aiographfix import Telegraph

tgh = Telegraph()

async def makeManga(sourcename, sourcelink, pool_obj, pool_content) -> str:
    
    await tgh.create_account('cumzoner')
    content = ''
    tlinks = []
    for i in pool_content:
        #try:
            #tlinks.append(await tgh.upload_from_url(i))
        #except Exception as E:
            #print(E, i)
        tlinks.append(i)
        
    if not tlinks: raise 'no tlinks'
    for i in tlinks:
        content += '<img src="{}"/>'.format(i)
    content += '<hr/>{}\nAutomatically generated by CUMZONER BOT'.format(pool_obj.description)
    page = await tgh.create_page(pool_obj.name.replace('_', ' '), content, author_name='{} pools'.format(sourcename), author_url = sourcelink)
    return page.url

async def makeTagsPage(tags, dbr_obj):
    await tgh.create_account('cumzoner')
    content = ''
    for i in tags:
        example_posts = dbr.posts(limit=3, random='true', tags = i, require_file_url = 1, ensure_count = 1)
        content += i
        for post in example_posts:
            content += '<img src="{}"/>'.format(post.file_url.link)
        content += '\n'
    page = await tgh.create_page('All tags', content[:1024 * 60])
    return page.url